telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    8464430657:AAHSP6GhumVBwdJVNO8492GAfnlS4TMgeao
#    используйте переменные среды для установки значений
    username: Crypto_appLesson_bot # ${BOT_NAME}
    token: 8464430657:AAHSP6GhumVBwdJVNO8492GAfnlS4TMgeao #${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

db:
  driver:
    name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/db
  user: root
  password: root
